repos:
-   repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
    - id: black
      args: ["--config=pyproject.toml", "--check"]
-   repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
    - id: flake8
      args: ["--config=.flake8"]
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
